# Dependencies
markdown:            kramdown
toc_levels:          1..2
highlighter:         rouge
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  parse_block_html: true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Jeremy Anifacc
tagline:             'α2Ω'
description:         'Life is an _if_ case & an accumulation!'
url:                 https://anifacc.github.io
baseurl:             https://anifacc.github.io/
paginate:            7

# About/contact
author:
  name:              Jeremy Anifacc
  url:               https://jeremiahzhang.github.io
  email:             zhangleisuda@gmail.com

# Custom vers
version:             3.0

# Social Media
github:				https://github.com/Anifacc
weibo:				http://weibo.com/ZhangXiaowoStef
disqus:				anifacc
twitter:			https://twitter.com/Jeremy_Anifacc

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Yixuan Li
  codename:			Geek-green
  link:         https://github.com/YixuanFranco
