# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yixuan
tagline:             'Mindhacker'
description:         '尘世间一只迷途小书虫.'
url:                 http://yixuan.li
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Yixuan Li
  url:               https://www.macundexiatian.com
  email:             liyixuan5402@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/YixuanFranco
twitter:			https://twitter.com/Yixuan5402
disqus:             @yixuan_li

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
